### ISSUE TITLE
Advanced quality settings: allow for target bitrate or specific quality level

### ISSUE THREAD

**Issue by hifihedgehog** [PaulLereverend/NextcloudVideo_Converter#15]
Though the presets are excellent for general usage, please add the option for more granularity with custom quality levels and target bitrates. Perhaps this could be accessed through an advanced quality settings section that is enabled by a checkbox?

**Comment by PaulLereverend** [comment]
Good idea but I have limited free time to work on this so it might take some time to be developped. I will keep this ticket open until the feature is done.

**Comment by hifihedgehog** [comment]
Totally understandable and thank you! Looking into the future, later down the roadmap, this would be a great nice-to-have.

**Comment by hifihedgehog** [comment]
You might want to consider switching to Handbrake CLI. Someone has some very interesting code out there that might help with that. :)

https://github.com/BurakBoz/handbrake-php

**Comment by githubDante** [comment]
Selectable bitrate support has been added with #29. It is not too complex, but it works :)

**Comment by hifihedgehog** [comment]
Closed, per the reply above. Special appreciation to @githubDante for making this invaluable contribution!
