### ISSUE TITLE
NC 17 compabitility

### ISSUE THREAD

**Issue by schniepp** [PaulLereverend/NextcloudVideo_Converter#21]
Please release for NC 17!

**Comment by PaulLereverend** [comment]
I will push an update this week end

**Comment by Schmuuu** [comment]
Hi,

I just wanted to let you know, that I tested the app with NC17 successfully. 
You can click "enable untested app" to afterwards enable the app. Enabling the app and converting a video worked flawlessly for me. No error messages in the logs.

**Comment by schniepp** [comment]
That's wonderful news! Thanks so much for looking into this so quickly!

**Comment by PaulLereverend** [comment]
Updated 😃 Feel free to let me know if something don't work.
