### ISSUE TITLE
Error:  Can't find file - extraction.js

### ISSUE THREAD

**Issue by tadepolejr** [PaulLereverend/NextcloudVideo_Converter#3]
Nextcloud version: 15.0.7

Installed NCVideo Converter

Tried to convert .mp4 video to .avi

NC log shows the following error: 
Could not find resource file "/cloud/apps/video_converter/js/extraction.js"

{"reqId":"LaijsSqfbhtudoZji9SX","level":0,"time":"2019-05-01T14:35:00-08:00","remoteAddr":"192.168.90.1","user":"adminxp583","app":"video_converter","method":"GET","url":"/nextcloud/index.php/apps/files/","message":"Could not find resource file \"/nextcloud/apps/video_converter/js/extraction.js\"","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15","version":"15.0.7.0","id":"5cc9f503b3e9d"}

**Comment by PaulLereverend** [comment]
Hi 

I saw this issue and I will fix it, but did the conversion work ? According to my tests, this error should not prevent the video from converting.

**Comment by tadepolejr** [comment]
Confirmed. Now the conversion is working. 
Thanks!
