### ISSUE TITLE
Error: Undefined variable: user

### ISSUE THREAD

**Issue by refgd** [PaulLereverend/NextcloudVideo_Converter#35]
Undefined variable: user at .../apps/video_converter/lib/Controller/ConversionController.php#44

**Comment by halleknast** [comment]
Seems to be caused by f0622e043255ff0eaf9e968307bfe3a7591c3f0c. Not really sure what that commit was for, it looks like a mistake to me.

**Comment by PaulLereverend** [comment]
Fixed in 229bc7a (latest update). Can you confirm ?

**Comment by halleknast** [comment]
Yes - thanks!
