### ISSUE TITLE
Change OC_Mount_Config for OCA\Files_External\MountConfig

### ISSUE THREAD

**Issue by MorrisJobke** [PaulLereverend/NextcloudVideo_Converter#49]
This app should migrate for Nextcloud 20 to OCA\Files_External\MountConfig.

See nextcloud/server#21785

Also the method `getExternalMP` does not need to be annotated with `@NoAdminRequired` - it's an internal method anyways only and it can be `protected` as well. In there just check for either the availability of `OCA\Files_External\MountConfig::getAbsoluteMountPoints` (for 20+) or `OC_Mount_Config:: getAbsoluteMountPoints ` (for everything up to 19). Also why do you need those private method calls? Best would be to not rely on internal methods private classes.

**Comment by MorrisJobke** [comment]
cc @PaulLereverend

**Comment by PaulLereverend** [comment]
Thoses methods are not used anymore on the latest update
