### ISSUE TITLE
No entry in files_rightclick app

### ISSUE THREAD

**Issue by Schmuuu** [PaulLereverend/NextcloudVideo_Converter#5]
Hello @PaulLereverend 

Awesome app! Simple, smooth and works perfectly.
Is it possible to integrate this app with the files_rightclick app and to get an entry in that rightclick menu? 
Or is this something I need to request from the right click app directly?

Thanks a lot for the good work!

**Comment by PaulLereverend** [comment]
Hi 

Thank you very much ! 😄
This app is integrated with the nextcloud's fileaction. The rightclick app does not display the fileaction but a custom menu on NC16 (it is working fine on NC15). Someone noticed that here https://github.com/nextcloud/files_rightclick/issues/61 and It was already fixed on 0.14.1 https://github.com/nextcloud/files_rightclick/blob/master/CHANGELOG.md but I don't know when it will be released. 

Meanwhile I will try to find another method to integrate on rightclick but I can not promise it will work.

**Comment by AaronADev** [comment]
I'm not sure if this issue needs to still be open. On Nextcloud 16.0.5 the actions are integrated with the files_rightclick app and they appear to be working just fine.

**Comment by Schmuuu** [comment]
@AaronADev you are right. Also in NC17 the entry appears now in the right click menu.
I'm closing this issue then. Thanks for the reminder!
