### ISSUE TITLE
Can't find file to convert if in Group Folder

### ISSUE THREAD

**Issue by AaronJWhite** [PaulLereverend/NextcloudVideo_Converter#57]
The app doesn't seem to support files stored in Group Folders. It tells me that it can't find the file if it's in a group folder and I notice that my user name is in the file path.
Group Folders App: https://apps.nextcloud.com/apps/groupfolders

**Comment by fernandopal** [comment]
Same isue here https://i.imgur.com/S8KIBAm.png, the files of this addon are stored under /__groupfolders and named by numbers (/__groupfolders/1/ /__groupfolders/2/ ...)

**Comment by AcidCrash1337** [comment]
This is a duplicate of #17.  See the thread there for the latest status.

**Comment by PaulLereverend** [comment]
Group folders are supported in the latest update.
