### ISSUE TITLE
No menu entry i NC20.0.1 - Bug?

### ISSUE THREAD

**Issue by nsrafk** [PaulLereverend/NextcloudVideo_Converter#58]
Hi.

I have enabled the app in my NC 20.0.1 instance but i get no option to convert file when right clicking on any. It was working when using NC v20. Anyone else having this issue?

**Comment by PaulLereverend** [comment]
Hi ! 
Do you still have this issue with NC 20.0.4 ?

**Comment by anon8675309** [comment]
I can confirm this issue exists on NC 20.0.2, which is the latest version available from apt repo at this time.

I do not currently have a test instance, and am not willing to go through the [15 step process](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html) of manually upgrading on my production instance (especially when the nextcloud docs are very clear that [downgrading is unsupported](https://docs.nextcloud.com/server/21/admin_manual/maintenance/upgrade.html) and may corrupt your data).  I'll try to remember to report back on this once 20.0.4 is available and I upgrade.

**Comment by anon8675309** [comment]
As a workaround, clicking the ellipsis on a file (as opposed to right clicking) did bring up the menu to convert the video.
