### ISSUE TITLE
nextcloud running in docker how to add ffmpeg?

### ISSUE THREAD

**Issue by wieluk** [PaulLereverend/NextcloudVideo_Converter#61]
My nextcloud is running in a docker can anyone tell me how I add ffmpeg ? I am using portainer and mostly stacks(docker-compose files)

**Comment by MikeRKing** [comment]
First access the docker container using;

docker exec -it <container name> bash
then;

apt-get update
apt-get install ffmpeg

**Comment by wieluk** [comment]
Thanks a lot

**Comment by wieluk** [comment]
#
