### ISSUE TITLE
faststart is not defined

### ISSUE THREAD

**Issue by Ami-OS** [PaulLereverend/NextcloudVideo_Converter#69]
https://github.com/PaulLereverend/NextcloudVideo_Converter/issues/67

I have the same problem and I viewed the source code, I think this a mistake :

https://github.com/PaulLereverend/NextcloudVideo_Converter/blob/a78018f0cf0495e9c5dd4232cf3339eb26aa59f5/js/conversion.js#L157

variable `faststart`, only defined on this line, but checkbox element need has been change then this line working :

https://github.com/PaulLereverend/NextcloudVideo_Converter/blob/a78018f0cf0495e9c5dd4232cf3339eb26aa59f5/js/conversion.js#L156-L158

So, if user using default (Not change element `#movflags`), `faststart` will never be defined.

## I think

I noted the checkbox element is `checked` default :

https://github.com/PaulLereverend/NextcloudVideo_Converter/blob/a78018f0cf0495e9c5dd4232cf3339eb26aa59f5/js/conversion.js#L111

So I think `faststart` can be defined at the beginning, like :

https://github.com/PaulLereverend/NextcloudVideo_Converter/blob/master/js/conversion.js
```
23 | var scaling = null;
+  | var faststart = true;
24 | $('body').append(
```

**Comment by hiro5id** [comment]
i have the same problem... plugin doesn't work anymore because of this javascript error (i think). I click on conversion buttons but nothing happens

**Comment by meonkeys** [comment]
Workaround: uncheck "Faststart option (for MP4)" in the conversion dialog box.

**Comment by Ami-OS** [comment]
yea, this is a temporary workaround.
but this is not great for users.

**Comment by PaulLereverend** [comment]
Fixed by the latest version.
